# Generated by Django 5.2.17 on 2026-08-16 10:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Зображення сертифіката')),
                ('pdf', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='PDF сертифіката')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показувати')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Сертифікат',
                'verbose_name_plural': 'Сертифікати',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
