# Generated by Django 5.2.17 on 2026-08-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_certificate_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Ім'я")),
                ('contact', models.CharField(max_length=150, verbose_name='Email або Telegram')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Опрацьовано')),
            ],
            options={
                'verbose_name': 'Заявка з контактної форми',
                'verbose_name_plural': 'Заявки з контактної форми',
                'ordering': ['-created_at'],
            },
        ),
    ]
